- name: Set up multiple authorized keys
  authorized_key:
    user: ec2-user
    state: present
    key: '{{ item }}'
  with_file:
    - public_keys/ec2-user.pub
    
- name: Install yum utils
  yum:
    name: yum-utils
    state: latest
 
- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest
 
- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: yes
 
- name: Install Docker
  package:
    name: docker-ce
    state: latest
  become: yes
 
- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
      
- name: Install latest Java 8
  yum: name=java-1.8.0-openjdk.x86_64 state=latest